### PR TITLE
add; spm support

### PR DESCRIPTION
**Pull request by popomore**
A nicer package manager: http://spmjs.io
Documentation: http://spmjs.io/documentation

http://spmjs.io/package/observed

---

It is a browser-side package manager popular in China, suppling a complete lifecycle managment of package via [spm](https://github.com/spmjs/spm/tree/master).

> If you need ownership of observed in spmjs, I can add it for your account after signing in http://spmjs.io.

spmjs/spm#781

### CODE REVIEW

**Comment by aheckmann** [comment]
merged. available in 1.1.1. Thanks

**Comment by popomore** [comment]
I want to add you as a maintainer in spmjs.io, would you like login from http://spmjs.io/login once?

**Comment by aheckmann** [comment]
I merged it but why not just use npm?

On Thu, Jan 15, 2015 at 9:12 AM, Haoliang Gao <notifications@github.com>
wrote:

> I want to add you as a maintainer in spmjs.io, would you like login from
> http://spmjs.io/login once?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aheckmann/observed/pull/17#issuecomment-70121469>.
>



-- 
Aaron
@aaronheckmann <https://twitter.com/#!/aaronheckmann>
soundcloud.com/ajhecky
github.com/aheckmann

**Comment by popomore** [comment]
Npm is slow in China, and spm only serves browser package.

**Comment by aheckmann** [comment]
what about the Chinese mirror cnpmjs.org? npm isn't limited to node modules btw.

—

**Comment by popomore** [comment]
Yes, but module will be conflicted between node and browser in npm. Browser modules will be hard to search.

**Pull request closed without merging**
